services:
  app:
    image: ${DOCKER_REGISTRY}/test:${DOCKER_BRANCH}
    container_name: ${DOCKER_BRANCH}-test
    environment:
      - TEST_KEY=$TEST_KEY
    networks:
      - traefik-realt
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.test-${DOCKER_BRANCH}.rule=Host(`${HOSTNAME}`)'
#      - 'traefik.http.routers.test-${DOCKER_BRANCH}.entrypoints=websecure'
      - 'traefik.http.services.test-${DOCKER_BRANCH}.loadbalancer.server.port=80'
    restart: always
    command: tail -f /dev/null

networks:
  traefik-realt:
    external: true
